In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [38]:
df1 = pd.read_csv('country_vaccinations.csv')

In [9]:
df2 = pd.read_csv('country_vaccinations_by_manufacturer.csv')

In [26]:
df1 = df1.drop(['iso_conde, source_name'])

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19111,Zimbabwe,ZWE,2021-05-15,793311.0,579769.0,213542.0,18070.0,19353.0,5.34,3.90,1.44,1302.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1395107134...
19112,Zimbabwe,ZWE,2021-05-16,796947.0,581615.0,215332.0,3636.0,16101.0,5.36,3.91,1.45,1083.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1395107134...
19113,Zimbabwe,ZWE,2021-05-17,814258.0,591808.0,222450.0,17311.0,17658.0,5.48,3.98,1.50,1188.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1395107134...
19114,Zimbabwe,ZWE,2021-05-18,831954.0,600579.0,231375.0,17696.0,17455.0,5.60,4.04,1.56,1174.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1395107134...
19115,Zimbabwe,ZWE,2021-05-19,844684.0,605556.0,239128.0,12730.0,16331.0,5.68,4.07,1.61,1099.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1395107134...

In [51]:
date = df1.groupby(['date'])

In [53]:
date.agg()

TypeError: Must provide 'func' or tuples of '(column, aggfunc).

In [64]:
date_df2 = df2.groupby(['location'])

In [65]:
date_df2.sum()

               total_vaccinations
location
Chile                   950155311
Czechia                 197943333
France                 1323014607
Germany                1755540035
Iceland                   8899607
Italy                  1258482215
Latvia                   18504052
Lithuania                62851946
Romania                 342041694
United States         16125269087